#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:XE
#    username: system
#    password: pass
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#
#    show-sql: true


spring:
  datasource:
    url: jdbc:mariadb://192.168.36.40:3306/DB_migration?useSSL=false&allowPublicKeyRetrieval=true
    username: djm
    password: qwer1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        # default_batch_fetch_size: 15
    database-platform: org.hibernate.dialect.MariaDBDialect